//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacionTutoriaPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class InformacionTutoriaPOJO : object
    {
        
        private string fechaEntregaField;
        
        private string fechaSesionField;
        
        private int idInformacionTutoriaField;
        
        private int idPeriodoEscolarField;
        
        private int noSesionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaEntrega
        {
            get
            {
                return this.fechaEntregaField;
            }
            set
            {
                this.fechaEntregaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaSesion
        {
            get
            {
                return this.fechaSesionField;
            }
            set
            {
                this.fechaSesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idInformacionTutoria
        {
            get
            {
                return this.idInformacionTutoriaField;
            }
            set
            {
                this.idInformacionTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPeriodoEscolar
        {
            get
            {
                return this.idPeriodoEscolarField;
            }
            set
            {
                this.idPeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int noSesion
        {
            get
            {
                return this.noSesionField;
            }
            set
            {
                this.noSesionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfesorPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class ProfesorPOJO : object
    {
        
        private int idProfesorField;
        
        private int idRolField;
        
        private string nombreField;
        
        private string numeroDeEmpleadoField;
        
        private string telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProfesor
        {
            get
            {
                return this.idProfesorField;
            }
            set
            {
                this.idProfesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRol
        {
            get
            {
                return this.idRolField;
            }
            set
            {
                this.idRolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroDeEmpleado
        {
            get
            {
                return this.numeroDeEmpleadoField;
            }
            set
            {
                this.numeroDeEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodoEscolarPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class PeriodoEscolarPOJO : object
    {
        
        private string descripcionFechaField;
        
        private int idPeriodoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionFecha
        {
            get
            {
                return this.descripcionFechaField;
            }
            set
            {
                this.descripcionFechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPeriodo
        {
            get
            {
                return this.idPeriodoField;
            }
            set
            {
                this.idPeriodoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramaEducativoPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class ProgramaEducativoPOJO : object
    {
        
        private int anioField;
        
        private string areaField;
        
        private string carreraField;
        
        private string claveField;
        
        private int idCoordinadorField;
        
        private int idProgramaEducativoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int anio
        {
            get
            {
                return this.anioField;
            }
            set
            {
                this.anioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carrera
        {
            get
            {
                return this.carreraField;
            }
            set
            {
                this.carreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCoordinador
        {
            get
            {
                return this.idCoordinadorField;
            }
            set
            {
                this.idCoordinadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProgramaEducativo
        {
            get
            {
                return this.idProgramaEducativoField;
            }
            set
            {
                this.idProgramaEducativoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TutoradoPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class TutoradoPOJO : object
    {
        
        private bool estaActivoField;
        
        private bool estaEnRiesgoField;
        
        private int idProgramaEducativoField;
        
        private int idTutoradoField;
        
        private string matriculaField;
        
        private string nombreField;
        
        private int numeroCambiosTutorField;
        
        private string telefonoField;
        
        private int tutorAcademicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estaActivo
        {
            get
            {
                return this.estaActivoField;
            }
            set
            {
                this.estaActivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estaEnRiesgo
        {
            get
            {
                return this.estaEnRiesgoField;
            }
            set
            {
                this.estaEnRiesgoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProgramaEducativo
        {
            get
            {
                return this.idProgramaEducativoField;
            }
            set
            {
                this.idProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutorado
        {
            get
            {
                return this.idTutoradoField;
            }
            set
            {
                this.idTutoradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula
        {
            get
            {
                return this.matriculaField;
            }
            set
            {
                this.matriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numeroCambiosTutor
        {
            get
            {
                return this.numeroCambiosTutorField;
            }
            set
            {
                this.numeroCambiosTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tutorAcademico
        {
            get
            {
                return this.tutorAcademicoField;
            }
            set
            {
                this.tutorAcademicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReporteTutoriaPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class ReporteTutoriaPOJO : object
    {
        
        private string descripcionField;
        
        private int idProgramaEducativoField;
        
        private int idReporteTutoriaField;
        
        private int idTutorField;
        
        private int idTutoradoField;
        
        private int idTutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProgramaEducativo
        {
            get
            {
                return this.idProgramaEducativoField;
            }
            set
            {
                this.idProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idReporteTutoria
        {
            get
            {
                return this.idReporteTutoriaField;
            }
            set
            {
                this.idReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutor
        {
            get
            {
                return this.idTutorField;
            }
            set
            {
                this.idTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutorado
        {
            get
            {
                return this.idTutoradoField;
            }
            set
            {
                this.idTutoradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutoria
        {
            get
            {
                return this.idTutoriaField;
            }
            set
            {
                this.idTutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo")]
    public partial class Mensaje : object
    {
        
        private bool confirmacionField;
        
        private ServiceReference1.HorarioTutoriaPOJO horarioTutoriaField;
        
        private ServiceReference1.InformacionTutoriaPOJO informacionTutoriaField;
        
        private string mensajeField;
        
        private ServiceReference1.ProblematicaAcademicaPOJO problematicaAcademicaField;
        
        private ServiceReference1.ProfesorPOJO profesorField;
        
        private ServiceReference1.ReporteTutoriaPOJO reporteTutoriaField;
        
        private ServiceReference1.SolucionPOJO solucionField;
        
        private ServiceReference1.TipoProblematicaPOJO tipoProblematicaField;
        
        private ServiceReference1.TutoradoPOJO tutoradoField;
        
        private ServiceReference1.UsuarioSesionPOJO usuarioSesionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool confirmacion
        {
            get
            {
                return this.confirmacionField;
            }
            set
            {
                this.confirmacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.HorarioTutoriaPOJO horarioTutoria
        {
            get
            {
                return this.horarioTutoriaField;
            }
            set
            {
                this.horarioTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.InformacionTutoriaPOJO informacionTutoria
        {
            get
            {
                return this.informacionTutoriaField;
            }
            set
            {
                this.informacionTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProblematicaAcademicaPOJO problematicaAcademica
        {
            get
            {
                return this.problematicaAcademicaField;
            }
            set
            {
                this.problematicaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProfesorPOJO profesor
        {
            get
            {
                return this.profesorField;
            }
            set
            {
                this.profesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ReporteTutoriaPOJO reporteTutoria
        {
            get
            {
                return this.reporteTutoriaField;
            }
            set
            {
                this.reporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.SolucionPOJO solucion
        {
            get
            {
                return this.solucionField;
            }
            set
            {
                this.solucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TipoProblematicaPOJO tipoProblematica
        {
            get
            {
                return this.tipoProblematicaField;
            }
            set
            {
                this.tipoProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TutoradoPOJO tutorado
        {
            get
            {
                return this.tutoradoField;
            }
            set
            {
                this.tutoradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.UsuarioSesionPOJO usuarioSesion
        {
            get
            {
                return this.usuarioSesionField;
            }
            set
            {
                this.usuarioSesionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HorarioTutoriaPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class HorarioTutoriaPOJO : object
    {
        
        private System.DateTime horarioTutoriaField;
        
        private int idTutorField;
        
        private int idTutoradoField;
        
        private int idTutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime horarioTutoria
        {
            get
            {
                return this.horarioTutoriaField;
            }
            set
            {
                this.horarioTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutor
        {
            get
            {
                return this.idTutorField;
            }
            set
            {
                this.idTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutorado
        {
            get
            {
                return this.idTutoradoField;
            }
            set
            {
                this.idTutoradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutoria
        {
            get
            {
                return this.idTutoriaField;
            }
            set
            {
                this.idTutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProblematicaAcademicaPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class ProblematicaAcademicaPOJO : object
    {
        
        private string descripcionField;
        
        private int idProblematicaField;
        
        private int idReporteTutoriaField;
        
        private int idTipoField;
        
        private int noIncidenciasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProblematica
        {
            get
            {
                return this.idProblematicaField;
            }
            set
            {
                this.idProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idReporteTutoria
        {
            get
            {
                return this.idReporteTutoriaField;
            }
            set
            {
                this.idReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipo
        {
            get
            {
                return this.idTipoField;
            }
            set
            {
                this.idTipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int noIncidencias
        {
            get
            {
                return this.noIncidenciasField;
            }
            set
            {
                this.noIncidenciasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolucionPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class SolucionPOJO : object
    {
        
        private string comentariosField;
        
        private string fechaSolucionField;
        
        private int idAcademicoField;
        
        private int idProblematicaField;
        
        private int idSolucionField;
        
        private int idTutoradoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comentarios
        {
            get
            {
                return this.comentariosField;
            }
            set
            {
                this.comentariosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaSolucion
        {
            get
            {
                return this.fechaSolucionField;
            }
            set
            {
                this.fechaSolucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAcademico
        {
            get
            {
                return this.idAcademicoField;
            }
            set
            {
                this.idAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProblematica
        {
            get
            {
                return this.idProblematicaField;
            }
            set
            {
                this.idProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSolucion
        {
            get
            {
                return this.idSolucionField;
            }
            set
            {
                this.idSolucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutorado
        {
            get
            {
                return this.idTutoradoField;
            }
            set
            {
                this.idTutoradoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoProblematicaPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class TipoProblematicaPOJO : object
    {
        
        private int idTipoProblematicaField;
        
        private string tipoProblematica1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipoProblematica
        {
            get
            {
                return this.idTipoProblematicaField;
            }
            set
            {
                this.idTipoProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoProblematica1
        {
            get
            {
                return this.tipoProblematica1Field;
            }
            set
            {
                this.tipoProblematica1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioSesionPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class UsuarioSesionPOJO : object
    {
        
        private string contraseñaField;
        
        private int idRolField;
        
        private int idUsuarioField;
        
        private string nombreField;
        
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña
        {
            get
            {
                return this.contraseñaField;
            }
            set
            {
                this.contraseñaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRol
        {
            get
            {
                return this.idRolField;
            }
            set
            {
                this.idRolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiciosProyectoTutorias")]
    public interface IServiciosProyectoTutorias
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RecuperarListaTutorias", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RecuperarListaTutoriasResponse")]
        System.Threading.Tasks.Task<ServiceReference1.InformacionTutoriaPOJO[]> RecuperarListaTutoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RecuperarListaTutores", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RecuperarListaTutoresResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ProfesorPOJO[]> RecuperarListaTutoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RecuperarPeriodosEscolares", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RecuperarPeriodosEscolaresResponse")]
        System.Threading.Tasks.Task<ServiceReference1.PeriodoEscolarPOJO[]> RecuperarPeriodosEscolaresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/ObtenerProgramaEducativo", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/ObtenerProgramaEducativoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ProgramaEducativoPOJO[]> ObtenerProgramaEducativoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RecuperarTutoradosSinTutor", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RecuperarTutoradosSinTutorResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TutoradoPOJO[]> RecuperarTutoradosSinTutorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RegistrarFechaTutoría", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RegistrarFechaTutoríaResponse")]
        System.Threading.Tasks.Task<bool> RegistrarFechaTutoríaAsync(ServiceReference1.InformacionTutoriaPOJO tutoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RegistrarProfesor", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RegistrarProfesorResponse")]
        System.Threading.Tasks.Task<bool> RegistrarProfesorAsync(ServiceReference1.ProfesorPOJO nuevoProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RegistrarTutorado", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RegistrarTutoradoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarTutoradoAsync(ServiceReference1.TutoradoPOJO nuevoTutorado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RegistrarReporteTutoria", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RegistrarReporteTutoriaResponse")]
        System.Threading.Tasks.Task<bool> RegistrarReporteTutoriaAsync(ServiceReference1.ReporteTutoriaPOJO nuevoReporteTutoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/EditarEstudiante", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/EditarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> EditarEstudianteAsync(ServiceReference1.TutoradoPOJO tutoradoAEdtitar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/iniciarSesion", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/iniciarSesionResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Mensaje> iniciarSesionAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServiciosProyectoTutoriasChannel : ServiceReference1.IServiciosProyectoTutorias, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiciosProyectoTutoriasClient : System.ServiceModel.ClientBase<ServiceReference1.IServiciosProyectoTutorias>, ServiceReference1.IServiciosProyectoTutorias
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiciosProyectoTutoriasClient() : 
                base(ServiciosProyectoTutoriasClient.GetDefaultBinding(), ServiciosProyectoTutoriasClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiciosProyectoTutorias.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosProyectoTutoriasClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiciosProyectoTutoriasClient.GetBindingForEndpoint(endpointConfiguration), ServiciosProyectoTutoriasClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosProyectoTutoriasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiciosProyectoTutoriasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosProyectoTutoriasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiciosProyectoTutoriasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosProyectoTutoriasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InformacionTutoriaPOJO[]> RecuperarListaTutoriasAsync()
        {
            return base.Channel.RecuperarListaTutoriasAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ProfesorPOJO[]> RecuperarListaTutoresAsync()
        {
            return base.Channel.RecuperarListaTutoresAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PeriodoEscolarPOJO[]> RecuperarPeriodosEscolaresAsync()
        {
            return base.Channel.RecuperarPeriodosEscolaresAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ProgramaEducativoPOJO[]> ObtenerProgramaEducativoAsync()
        {
            return base.Channel.ObtenerProgramaEducativoAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TutoradoPOJO[]> RecuperarTutoradosSinTutorAsync()
        {
            return base.Channel.RecuperarTutoradosSinTutorAsync();
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarFechaTutoríaAsync(ServiceReference1.InformacionTutoriaPOJO tutoria)
        {
            return base.Channel.RegistrarFechaTutoríaAsync(tutoria);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarProfesorAsync(ServiceReference1.ProfesorPOJO nuevoProfesor)
        {
            return base.Channel.RegistrarProfesorAsync(nuevoProfesor);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarTutoradoAsync(ServiceReference1.TutoradoPOJO nuevoTutorado)
        {
            return base.Channel.RegistrarTutoradoAsync(nuevoTutorado);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarReporteTutoriaAsync(ServiceReference1.ReporteTutoriaPOJO nuevoReporteTutoria)
        {
            return base.Channel.RegistrarReporteTutoriaAsync(nuevoReporteTutoria);
        }
        
        public System.Threading.Tasks.Task<bool> EditarEstudianteAsync(ServiceReference1.TutoradoPOJO tutoradoAEdtitar)
        {
            return base.Channel.EditarEstudianteAsync(tutoradoAEdtitar);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Mensaje> iniciarSesionAsync(string username, string password)
        {
            return base.Channel.iniciarSesionAsync(username, password);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiciosProyectoTutorias))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiciosProyectoTutorias))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56022/ServiciosProyectoTutorias.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiciosProyectoTutoriasClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiciosProyectoTutorias);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiciosProyectoTutoriasClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiciosProyectoTutorias);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiciosProyectoTutorias,
        }
    }
}
