//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceBackendTutorias
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacionTutoriaPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class InformacionTutoriaPOJO : object
    {
        
        private string fechaEntregaField;
        
        private string fechaSesionField;
        
        private int idInformacionTutoriaField;
        
        private int idPeriodoEscolarField;
        
        private int noSesionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaEntrega
        {
            get
            {
                return this.fechaEntregaField;
            }
            set
            {
                this.fechaEntregaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaSesion
        {
            get
            {
                return this.fechaSesionField;
            }
            set
            {
                this.fechaSesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idInformacionTutoria
        {
            get
            {
                return this.idInformacionTutoriaField;
            }
            set
            {
                this.idInformacionTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPeriodoEscolar
        {
            get
            {
                return this.idPeriodoEscolarField;
            }
            set
            {
                this.idPeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int noSesion
        {
            get
            {
                return this.noSesionField;
            }
            set
            {
                this.noSesionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfesorPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class ProfesorPOJO : object
    {
        
        private int idProfesorField;
        
        private int idRolField;
        
        private string nombreField;
        
        private string numeroDeEmpleadoField;
        
        private string telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProfesor
        {
            get
            {
                return this.idProfesorField;
            }
            set
            {
                this.idProfesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRol
        {
            get
            {
                return this.idRolField;
            }
            set
            {
                this.idRolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroDeEmpleado
        {
            get
            {
                return this.numeroDeEmpleadoField;
            }
            set
            {
                this.numeroDeEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TutoradoPOJO", Namespace="http://schemas.datacontract.org/2004/07/ProyectoTutorias.Modelo.POJO")]
    public partial class TutoradoPOJO : object
    {
        
        private bool estaActivoField;
        
        private bool estaEnRiesgoField;
        
        private int idProgramaEducativoField;
        
        private int idTutoradoField;
        
        private string matriculaField;
        
        private string nombreField;
        
        private int numeroCambiosTutorField;
        
        private string telefonoField;
        
        private int tutorAcademicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estaActivo
        {
            get
            {
                return this.estaActivoField;
            }
            set
            {
                this.estaActivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estaEnRiesgo
        {
            get
            {
                return this.estaEnRiesgoField;
            }
            set
            {
                this.estaEnRiesgoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProgramaEducativo
        {
            get
            {
                return this.idProgramaEducativoField;
            }
            set
            {
                this.idProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutorado
        {
            get
            {
                return this.idTutoradoField;
            }
            set
            {
                this.idTutoradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula
        {
            get
            {
                return this.matriculaField;
            }
            set
            {
                this.matriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numeroCambiosTutor
        {
            get
            {
                return this.numeroCambiosTutorField;
            }
            set
            {
                this.numeroCambiosTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tutorAcademico
        {
            get
            {
                return this.tutorAcademicoField;
            }
            set
            {
                this.tutorAcademicoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBackendTutorias.IServiciosProyectoTutorias")]
    public interface IServiciosProyectoTutorias
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RecuperarListaTutorias", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RecuperarListaTutoriasResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBackendTutorias.InformacionTutoriaPOJO[]> RecuperarListaTutoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RecuperarListaTutores", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RecuperarListaTutoresResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBackendTutorias.ProfesorPOJO[]> RecuperarListaTutoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RegistrarFechaTutoría", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RegistrarFechaTutoríaResponse")]
        System.Threading.Tasks.Task<bool> RegistrarFechaTutoríaAsync(ServiceReferenceBackendTutorias.InformacionTutoriaPOJO tutoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RegistrarProfesor", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RegistrarProfesorResponse")]
        System.Threading.Tasks.Task<bool> RegistrarProfesorAsync(ServiceReferenceBackendTutorias.ProfesorPOJO nuevoProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosProyectoTutorias/RegistrarTutorado", ReplyAction="http://tempuri.org/IServiciosProyectoTutorias/RegistrarTutoradoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarTutoradoAsync(ServiceReferenceBackendTutorias.TutoradoPOJO nuevoTutorado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServiciosProyectoTutoriasChannel : ServiceReferenceBackendTutorias.IServiciosProyectoTutorias, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiciosProyectoTutoriasClient : System.ServiceModel.ClientBase<ServiceReferenceBackendTutorias.IServiciosProyectoTutorias>, ServiceReferenceBackendTutorias.IServiciosProyectoTutorias
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiciosProyectoTutoriasClient() : 
                base(ServiciosProyectoTutoriasClient.GetDefaultBinding(), ServiciosProyectoTutoriasClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiciosProyectoTutorias.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosProyectoTutoriasClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiciosProyectoTutoriasClient.GetBindingForEndpoint(endpointConfiguration), ServiciosProyectoTutoriasClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosProyectoTutoriasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiciosProyectoTutoriasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosProyectoTutoriasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiciosProyectoTutoriasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosProyectoTutoriasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBackendTutorias.InformacionTutoriaPOJO[]> RecuperarListaTutoriasAsync()
        {
            return base.Channel.RecuperarListaTutoriasAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBackendTutorias.ProfesorPOJO[]> RecuperarListaTutoresAsync()
        {
            return base.Channel.RecuperarListaTutoresAsync();
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarFechaTutoríaAsync(ServiceReferenceBackendTutorias.InformacionTutoriaPOJO tutoria)
        {
            return base.Channel.RegistrarFechaTutoríaAsync(tutoria);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarProfesorAsync(ServiceReferenceBackendTutorias.ProfesorPOJO nuevoProfesor)
        {
            return base.Channel.RegistrarProfesorAsync(nuevoProfesor);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarTutoradoAsync(ServiceReferenceBackendTutorias.TutoradoPOJO nuevoTutorado)
        {
            return base.Channel.RegistrarTutoradoAsync(nuevoTutorado);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiciosProyectoTutorias))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiciosProyectoTutorias))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56022/ServiciosProyectoTutorias.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiciosProyectoTutoriasClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiciosProyectoTutorias);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiciosProyectoTutoriasClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiciosProyectoTutorias);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiciosProyectoTutorias,
        }
    }
}
